version: '3.8'

services:
  intershop-service:
    build: ./intershop-service
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - intershop-network

  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"
    networks:
      - intershop-network
  redis:
    image: redis:7.0-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "6379:6379"
    networks:
      - intershop-network


networks:
  intershop-network:
    driver: bridge